### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by OisinMoran** [bartvm/mimir#7]
When running through the `README.md` in [Deep Complex Networks](https://github.com/ChihebTrabelsi/deep_complex_networks), which utilizes Mímir for logging, I am met with this error:

```bash
Traceback (most recent call last):
  File "/home/oisin/DCN/bin/train.py", line 4, in <module>
    __import__('pkg_resources').run_script('DeepComplexNetworks==1', 'train.py')
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/DeepComplexNetworks-1-py2.7.egg/EGG-INFO/scripts/train.py", line 142, in <module>
    
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/DeepComplexNetworks-1-py2.7.egg/EGG-INFO/scripts/train.py", line 112, in main
    
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/mimir/logger.py", line 71, in Logger
    handlers.append(GzipJSONHandler(root))
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/mimir/handlers.py", line 134, in __init__
    stream = gzlog.GZipLog(filename)
  File "gzlog/gzlog.pyx", line 89, in mimir.gzlog.GZipLog.__init__
  File "gzlog/gzlog.pyx", line 26, in mimir.gzlog.Gzlog.__cinit__
IOError
```

which I have been unable to resolve. Any help at all in trying to fix this would be greatly appreciated!

**Comment by OisinMoran** [comment]
This was not in fact an issue with Mímir, but with a hard-coded file path, and has been resolved.
[Linked issue](https://github.com/ChihebTrabelsi/deep_complex_networks/issues/20)

**Comment by OisinMoran** [comment]
I don't think this is an issue with Mímir, but rather just a missing folder as described [here](https://github.com/ChihebTrabelsi/deep_complex_networks/issues/20).
