### ISSUE TITLE
UnicodeDecodeError installing

### ISSUE THREAD

**Issue by austinmw** [bartvm/mimir#8]
When I try to run `pip install git+git://github.com/bartvm/mimir.git` I get the error:

```
Collecting git+git://github.com/bartvm/mimir.git
  Cloning git://github.com/bartvm/mimir.git to /tmp/pip-6C09DZ-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-6C09DZ-build/setup.py", line 14, in <module>
        long_description=readme(),
      File "/tmp/pip-6C09DZ-build/setup.py", line 8, in readme
        return f.read()
      File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```
Any idea how to fix this?

**Comment by austinmw** [comment]
Fixed by removing these lines from `setup.py`:

```
    long_description=readme(),
    url='https://github.com/bartvm/mimir',
    author='Bart van Merriënboer',
    author_email='bart.vanmerrienboer@gmail.com',
```

**Comment by bartvm** [comment]
The offending string will be my name, Merriënboer, which Python 2 might choke on. Changing it to `u'Bart van Merriënboer'` should work, and Python 3 should work just fine as well.

**Comment by austinmw** [comment]
I took your name out but still got the error so figured there was another non-ascii char in the readme

**Comment by bartvm** [comment]
Ah, yeah, the readme has Mímir with an accent
